version: "3"
services:

  guacd:
    image: guacamole/guacd:latest
    restart: always
    networks:
      - guacnet

  db:
    image: glyptodon/guacamole-db-mysql:latest
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      ACCEPT_EULA: "Y"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      GUACAMOLE_DATABASE: guacamole_db
      GUACAMOLE_USERNAME: guacamole_user
      GUACAMOLE_PASSWORD: $GUACPASS
    networks:
      - guacnet

  guacamole:
    image: guacamole/guacamole:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /config
    environment:
      MYSQL_HOSTNAME: db
      MYSQL_SSL_MODE: disabled
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: $GUACPASS
      GUACAMOLE_HOME: /config
      GUACD_HOSTNAME: guacd
    networks:
      - guacnet
    depends_on:
      - db
      - guacd

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
networks:
  guacnet:
  