version: "3"
services:

  guacd:
    image: guacamole/guacd:1.3.0

  db:
    image: glyptodon/guacamole-db-mysql:2
    volumes:
      - ./db:/var/lib/mysql
    environment:
      ACCEPT_EULA: "Y"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      GUACAMOLE_DATABASE: guacamole_db
      GUACAMOLE_USERNAME: guacamole_user
      GUACAMOLE_PASSWORD: $GUACPASS

  guacamole:
    image: guacamole/guacamole:1.3.0
    volumes:
      - /config
    environment:
      MYSQL_HOSTNAME: db
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: $GUACPASS
      GUACAMOLE_HOME: /config
      GUACD_HOSTNAME: guacd

  ssl:
    image: glyptodon/guacamole-ssl-nginx:2
    ports:
      - "80:80"
      - "443:443"
    environment:
      ACCEPT_EULA: "Y"
      GUACAMOLE_HOSTNAME: guacamole
      GUACAMOLE_CONTEXT_PATH: "guacamole"
      SSL_HOSTNAME: $HOSTNAME
      SELF_SIGNED: "Y"
      #LETSENCRYPT_ACCEPT_TOS: "Y"
      #LETSENCRYPT_EMAIL: $EMAIL
